runtime: python312
service: notes-123230181

handlers:
  - url: /(.+\.(css|js|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf))
    static_files: \1
    upload: .+\.(css|js|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf)

  - url: /.*
    static_files: index.html
    upload: index.html
